---
- name: to pull image and start docker container
  hosts: docker

  tasks:
    - name: to login into ws ecr
      shell: $(aws ecr get-login --no-include-email)
    - name: to pull docker image
      shell: docker pull 018479218481.dkr.ecr.ap-south-1.amazonaws.com/app:1
    - name: to start docker container
      shell: docker run --name=con1 -itd -p 8080:8080 018479218481.dkr.ecr.ap-south-1.amazonaws.com/app:1
