- name: playbook
  hosts: all_slaves
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: check aws connect
      shell: aws s3 ls

    - name: Login to AWS ECR
      shell: $(aws ecr get-login --no-include-email)

    - name: Pull docker image
      shell: docker pull 899197664719.dkr.ecr.ap-south-1.amazonaws.com/app:latest
    
    - name: start docker container
      shell: docker run --name con1 -itd -p 8080:8080 899197664719.dkr.ecr.ap-south-1.amazonaws.com/app:latest
