- name: Pipeline process
  hosts: all_slaves
   
  tasks:
    - name: pull docker images from AWS ECR
      shell: docker pull 899197664719.dkr.ecr.ap-south-1.amazonaws.com/app:latest

    - name: stop container
      shell: docker stop con1

    - name: remove container
      shell: docker rm con1

    - name: start docker container
      shell: docker run --name con1 -itd -p 8080:8080 899197664719.dkr.ecr.ap-south-1.amazonaws.com/app:latest
