---
- name: to deply app in docker
  hosts: tag_Name_docker

  tasks:
    - name: to login into AWS ECR
      shell: $(aws ecr get-login --no-include-email)

    - name: to download docker images
      shell: docker pull 303627538160.dkr.ecr.ap-south-1.amazonaws.com/app:latest

    - name: to start container
      shell: docker run --name=con1 -itd -p 8080:8080 303627538160.dkr.ecr.ap-south-1.amazonaws.com/app:latest
