---
- name: to install app service
  hosts: app_servers

  tasks:
    - name: Install java
      yum:
        name: java
        state: installed

    - name: to check tomcat service
      stat:
        path: /usr/share/tomcat
      register: app_var

    - name: Tomcat not Installed
      debug:
        msg: Tomcat is NOT install
      when: app_var.stat.exists == false

    - name: Tomcat Installed
      debug:
        msg: Tomcat Installed
      when: app_var.stat.exists == true

    - name: to install tomcat
      yum:
        name: tomcat
        state: installed
      when: app_var.stat.exists == false

    - name: check tomcat service installed or not
      stat:
        path: /usr/share/tomcat
      register: app_var
    
    - name: start tomcat service
      service:
        name: tomcat
        state: started
      when: app_var.stat.exists == true

    - name: deploy
      copy:
        src: target/mvn-hello-world.war
        dest: /usr/share/tomcat/webapps/


    
