---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appserver
spec:
  selector:
    matchLabels:
      app: appserver
  replicas: 0
  template:
    metadata:
      labels:
        app: appserver
    spec:
      containers:
        - name: appserver
          image: 018479218481.dkr.ecr.ap-south-1.amazonaws.com/app:1
          ports:
            - containerPort: 8080
