---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  selector:
    matchLabels:
      app: mydeployment
  replicas: 1
  template:
    metadata:
      labels:
        app: mydeployment
    spec:
      containers:
        - name: mydeployment
          image: 559584465773.dkr.ecr.ap-south-1.amazonaws.com/myapp:1
          ports:
            - containerPort: 8080
