---
- name: Docker ENgine playbook
  hosts: docker_eng

  tasks:
    - name: connect to Docker ENg & login to AWS ECR
      shell: $(aws ecr get-login --no-include-email)

    - name: pull docker image
      shell: docker pull 303627538160.dkr.ecr.ap-south-1.amazonaws.com/app:1

    - name: STart Docker container
      shell: docker run --name=con1 -itd -p 8080:8080 303627538160.dkr.ecr.ap-south-1.amazonaws.com/app:1
