---
- name: to pull image and start container
  hosts: docker_slaves

  tasks:
    - name: login to AWS ECR
      shell: $(aws ecr get-login --no-include-email)

    - name: Pull docker image
      shell: docker pull 592300148445.dkr.ecr.ap-south-1.amazonaws.com/app:latest

    - name: start docker container
      shell: docker run --name con1 -itd -p 8080:8080 592300148445.dkr.ecr.ap-south-1.amazonaws.com/app:latest
