---
- name: for Docker Engine
  hosts: docker_eng

  tasks:
    - name: login to aws ecr
      shell: $(aws ecr get-login --no-include-email)
      
    - name: pull image from docker hub
      shell: docker pull 480756542354.dkr.ecr.ap-south-1.amazonaws.com/app:latest

    - name: Stop if any container is running on same name
      shell: docker stop con1

    - name: Remove if any container is available
      shell: docker rm con1
    
    - name: start docker container
      shell: docker run --name=con1 -itd -p 8080:8080 480756542354.dkr.ecr.ap-south-1.amazonaws.com/app:latest
