---
- name: to do in both de
  hosts: tag_Name_DE1

  tasks:
    - name: to connect to AWS ECR registry
      shell: $(aws ecr get-login --no-include-email)

    - name: to pull docker image
      shell:  docker pull 480756542354.dkr.ecr.ap-south-1.amazonaws.com/app:latest

    - name: to start docker container
      shell: docker run --name mycon -itd -p 8080:8080 480756542354.dkr.ecr.ap-south-1.amazonaws.com/app:latest
